
version: 2

sources:
  - name: sales_car
    description: Replica of the Postgres database used by the transactional system.

    tables:
      - name: orders
        description: This table contains informarion about orders.
        columns:
          - name: id
            description: Primary key of the orders table.
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Foreing Key of the customers table.
            tests:
              - not_null
          - name: departament_id
            description: Foreing Key of column departament in employees table.
          - name: order_type_id
            description: Foreing Key of the order type table.
            tests:
              - not_null
          - name: order_status
            description: Description of the order status in orders table.
            tests:
              - accepted_values:
                  values: ['on hold', 'shipped', 'pending', 'delayed']

      - name: order_types
        description: This table contains informarion about order types.
      
      - name: order_items
        description: This table contains informarion about order items.
      
      - name: company_branches
        description: This table contains informarion about company branches.

  - name: seeds
    description: Data coming from .csv files with additional information provided by the business teams

    tables:
      - name: customers
        description: This is a replica of the customers file.csv.
        
      - name: employees
        description: This is a replica of the employees file.csv.
